function gen = generate_0(g, p)
    %GENERATE_O checks if a natural number g is generating set of a
    %multiplicative group determined by the prime number p.
    %NOTE: Brute force algorithm.
    %   GEN = GENERATE_O(G, P) returns:
    %       - 0: if the number is not a generating set of a group.
    %       - g: if g is a generator number.

    tic
    
    g = uint64(g);
    p = uint64(p);
    gen = 0;
    
    % Fp_star = (Zp -{0},·). Set to be generated by g.
    Fp_star = 1:(p - 1);
    
    % Compute the (p - 1) powers of g.
    set = [p - 1];
    for i = 1:(p - 1)
        set(i) = power_mod(g, i, p);
    end
    
    set = unique(set);

    % Compare both sets.
    if isequal(Fp_star, set)
        gen = g;
    end
    
    toc
end

